export const image = {
  logo: require("../assetss/logo.svg").default,
  1: require("../assetss/1.jpg").default,
  2: require("../assetss/2.jpg").default,
  3: require("../assetss/3.jpg").default,
  b1: require("../assetss/b1.jpg").default,
  b2: require("../assetss/b2.jpg").default,
  b3: require("../assetss/b3.jpg").default,
  banner1: require("../assetss/banner1.jpeg").default,
  banner2: require("../assetss/banner2.jpeg").default,
  bonus: require("../assetss/bonus.png").default,
  gonzoa: require("../assetss/gonzoa.png").default,
  crazy: require("../assetss/crazy.png").default,
  images: require("../assetss/footer.png").default,
  fund: require("../assetss/fund.png").default,
  topHours: require("../assetss/top-hours.png").default,
  provider: require("../assetss/provider.svg").default,
  wave: require("../assetss/wave.svg").default,
  sliderCasino1: require("../assetss/slider-casino-1.png").default,
  sliderCasino2: require("../assetss/slider-casino-2.png").default,
  sliderCasino3: require("../assetss/slider-casino-3.png").default,
  svgImage: require("../assetss/svgImage.svg").default,
};
export default image;
